### ISSUE TITLE
Still in development?

### ISSUE THREAD

**Issue by aria-blackford** [dmntk/dmntk.rs#31]
Is this still in development? I note that it's been a while since the last commit.

**Comment by dmntk** [comment]
We have just released first beta version. 99.9% of compatibility tests are passing. Failing tests are using model imports that are currently developed and will be available in version 0.2.0. 90% of models from compatibility tests execute in less than 5 microseconds (Rust benchmarks), of course the latency depends on the machine. When used as a service you have to add time spent on TCP communication, but this may be optimized in many ways. So, as you have written, you need to execute models million times, so I guess with single DMNTK server it could take ~3..100 seconds. Of course running multiple servers will make it better. DMNTK can be optimized with binary size by compiling using Rust on the target operating system. DMNTK is coud-ready, may be initialized in any container using environment variables. Documentation is now rudimentary, but I am ready to help 24/7/365 if needed.
