### ISSUE TITLE
Dockerfile can't do dmntk srv 

### ISSUE THREAD

**Issue by marc4gov** [dmntk/dmntk.rs#45]
Hi,

I try to use `dmntk` in a Docker file, but I noticed the standalone command `dmntk` works as expected, but `dmntk srv` gives this error:

`ERROR: for dmntk  Cannot start service dmntk: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "dmntk srv": executable file not found in $PATH: unknown`

Something to do with spawning a webserver inside a Docker container...?

Here's the Dockerfile:

```
# Use a base image with the latest version of Rust installed
FROM rust:latest

# Set the working directory in the container
WORKDIR /app

# Copy the local application code into the container
COPY . .

# Build the Rust application
RUN cargo install dmntk

ENV PATH="${PATH}:$HOME/.cargo/bin"

# Specify the command to run when the container starts
CMD ["dmntk srv"]
```

**Comment by dmntk** [comment]
Please, let me know if it worked ;-)

**Comment by marc4gov** [comment]
Hi Darek,

Thanks for helping me out here. It works! Also, I like dmntk a lot, it's DMN execution is blazing fast...

Keep up the good work!

Cheers, Marc

**Comment by dmntk** [comment]
Hi Marc,

It's my pleasure to help :-) and I am keeping doing my best ;-)
I am closing this issue as resolved, but if there is anything I could do better, just let me know.
Could you help me with this project just by giving a star :-) :-) :-) Thanks in advance.
I am preparing now a next version with some changes that may possibly impact your project.
Would you share your e-mail address that I can send you short notice when I am ready?
Thanks a lot!

Cheers, Darek

**Comment by marc4gov** [comment]
this my email

Op wo 10 mei 2023 om 09:41 schreef DMNTK ***@***.***>:
